### ISSUE TITLE
issues with: Learning to Play Acrobot with Actor-Critic

### ISSUE THREAD

**Issue by piteren** [shakedzy/notebooks#2]
Hi,
I have found one issue with 'Learning to Play Acrobot with Actor-Critic' notebook. Please check it out and let me know if I'm right:
You call learning method (actor_cost, critic_cost = ac.learn(sess)) with every step of game play - it means that update is not done in batches, although your networks (Actor and Critc) are build properly to update with batches of data (placeholders have batch axis).

**Comment by shakedzy** [comment]
Hi @piteren - quoting the notebook (just above `In [10]`):

> Time to train! The Actor-Critic mechanism allows us to train at any step, without waiting for the episode to end. **Let's train the Agent after every action it takes.**

**Comment by piteren** [comment]
Ok, I see, so what is memory for? Why do you sample batch from memory of size 1.? Is not training with batches more stable for NN?

**Comment by shakedzy** [comment]
I guess you can train on larger batches, I've decided to use batches of size 1 here
